### ISSUE TITLE
parking a little to close to the fruit

### ISSUE THREAD

**Issue by abehnke** [netjungle/courseplay#45] opened 2013-01-24 17:17 UTC
I have been doing some testing using barley, beets and Big X cornchopper.  No collisions between equipment! The only thing I see is that after the tipper U turn to wait for more, the barley and beet course leaves the tipper parked a little too close to the fruit.  It seems to happen almost all the time with beets but rarely with barley.  Attached are 2 images.

I am using a ZIP file that I downloaded from github on Jan. 24, 2013.  

Thank you and your colleagues for updating the Courseplay.

![beets2](https://f.cloud.github.com/assets/3346683/94398/bdbf1aca-6649-11e2-8a55-ad4cfaefab13.png)

![grain](https://f.cloud.github.com/assets/3346683/94401/c7b548a6-6649-11e2-9eed-0c694ff736b5.png)

**Comment by abehnke** [comment] 2013-01-24 19:44
I looked into seeing if I could add an offset (local x) to the U turn parking for the tipper (in the area of line 431 in mode2.lua) .  For the beet (and possibly potato), this is does not seem to be possible at the moment. To do this, I need to reliably know which side the fruit is on. As you said in another post, have to wait for documentation from the FS13 developer.

**Comment by JakobTischler** [comment] 2013-01-27 10:07
I'm testing different turn maneuvers these days, some with some success, some with less. It's rather hard to find the one turn maneuver that rules them all, one that applies to any of the tractors, with any tipper attached.

So, this is rather a matter of time and testing - we know the problem, we know the cause, we just need a solution :)

**Comment by DirkSch** [comment] 2013-02-13 15:48
The problem is still the Grimme Maxtron and Grimme Tectron. The tractor stops in the fruit in front of harvester

**Comment by ThomasGaertner** [comment] 2013-02-14 19:01
fixed with : "improved truning maneuver after unloading combine"
closed

**Closed as completed by ThomasGaertner** 2013-02-14 19:01 UTC
Labels: reviewed
